/*
 * This file is generated by jOOQ.
 */
package domains.tables.records;


import domains.tables.Employees;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeesRecord extends UpdatableRecordImpl<EmployeesRecord> implements Record7<Integer, Integer, Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Employees.employee_id</code>.
     */
    public void setEmployeeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Employees.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Employees.post</code>.
     */
    public void setPost(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Employees.post</code>.
     */
    public Integer getPost() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Employees.branch</code>.
     */
    public void setBranch(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Employees.branch</code>.
     */
    public Integer getBranch() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Employees.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Employees.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Employees.last_name</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Employees.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Employees.service_number</code>.
     */
    public void setServiceNumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>Employees.service_number</code>.
     */
    public String getServiceNumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>Employees.role</code>.
     */
    public void setRole(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>Employees.role</code>.
     */
    public Integer getRole() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, String, String, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, String, String, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Employees.EMPLOYEES.EMPLOYEE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Employees.EMPLOYEES.POST;
    }

    @Override
    public Field<Integer> field3() {
        return Employees.EMPLOYEES.BRANCH;
    }

    @Override
    public Field<String> field4() {
        return Employees.EMPLOYEES.FIRST_NAME;
    }

    @Override
    public Field<String> field5() {
        return Employees.EMPLOYEES.LAST_NAME;
    }

    @Override
    public Field<String> field6() {
        return Employees.EMPLOYEES.SERVICE_NUMBER;
    }

    @Override
    public Field<Integer> field7() {
        return Employees.EMPLOYEES.ROLE;
    }

    @Override
    public Integer component1() {
        return getEmployeeId();
    }

    @Override
    public Integer component2() {
        return getPost();
    }

    @Override
    public Integer component3() {
        return getBranch();
    }

    @Override
    public String component4() {
        return getFirstName();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public String component6() {
        return getServiceNumber();
    }

    @Override
    public Integer component7() {
        return getRole();
    }

    @Override
    public Integer value1() {
        return getEmployeeId();
    }

    @Override
    public Integer value2() {
        return getPost();
    }

    @Override
    public Integer value3() {
        return getBranch();
    }

    @Override
    public String value4() {
        return getFirstName();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public String value6() {
        return getServiceNumber();
    }

    @Override
    public Integer value7() {
        return getRole();
    }

    @Override
    public EmployeesRecord value1(Integer value) {
        setEmployeeId(value);
        return this;
    }

    @Override
    public EmployeesRecord value2(Integer value) {
        setPost(value);
        return this;
    }

    @Override
    public EmployeesRecord value3(Integer value) {
        setBranch(value);
        return this;
    }

    @Override
    public EmployeesRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public EmployeesRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public EmployeesRecord value6(String value) {
        setServiceNumber(value);
        return this;
    }

    @Override
    public EmployeesRecord value7(Integer value) {
        setRole(value);
        return this;
    }

    @Override
    public EmployeesRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesRecord
     */
    public EmployeesRecord() {
        super(Employees.EMPLOYEES);
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(Integer employeeId, Integer post, Integer branch, String firstName, String lastName, String serviceNumber, Integer role) {
        super(Employees.EMPLOYEES);

        setEmployeeId(employeeId);
        setPost(post);
        setBranch(branch);
        setFirstName(firstName);
        setLastName(lastName);
        setServiceNumber(serviceNumber);
        setRole(role);
    }
}
