/*
 * This file is generated by jOOQ.
 */
package domains.tables.records;


import domains.tables.Roles;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesRecord extends UpdatableRecordImpl<RolesRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Roles.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Roles.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Roles.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Roles.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Roles.is_administration</code>.
     */
    public void setIsAdministration(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Roles.is_administration</code>.
     */
    public Integer getIsAdministration() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Roles.ROLES.ROLE_ID;
    }

    @Override
    public Field<String> field2() {
        return Roles.ROLES.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Roles.ROLES.IS_ADMINISTRATION;
    }

    @Override
    public Integer component1() {
        return getRoleId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getIsAdministration();
    }

    @Override
    public Integer value1() {
        return getRoleId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getIsAdministration();
    }

    @Override
    public RolesRecord value1(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RolesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public RolesRecord value3(Integer value) {
        setIsAdministration(value);
        return this;
    }

    @Override
    public RolesRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesRecord
     */
    public RolesRecord() {
        super(Roles.ROLES);
    }

    /**
     * Create a detached, initialised RolesRecord
     */
    public RolesRecord(Integer roleId, String name, Integer isAdministration) {
        super(Roles.ROLES);

        setRoleId(roleId);
        setName(name);
        setIsAdministration(isAdministration);
    }
}
