/*
 * This file is generated by jOOQ.
 */
package domains;


import domains.tables.Branches;
import domains.tables.Employeeanswers;
import domains.tables.Employees;
import domains.tables.Tests;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BRANCHES_ORGANIZATION_ID_UINDEX = Internal.createIndex(DSL.name("Branches_organization_id_uindex"), Branches.BRANCHES, new OrderField[] { Branches.BRANCHES.ORGANIZATION_ID }, true);
    public static final Index EMPLOYEEANSWERS_TESTING_UINDEX = Internal.createIndex(DSL.name("EmployeeAnswers_testing_uindex"), Employeeanswers.EMPLOYEEANSWERS, new OrderField[] { Employeeanswers.EMPLOYEEANSWERS.TESTING }, true);
    public static final Index EMPLOYEES_BRANCH_UINDEX = Internal.createIndex(DSL.name("Employees_branch_uindex"), Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.BRANCH }, true);
    public static final Index EMPLOYEES_POST_UINDEX = Internal.createIndex(DSL.name("Employees_post_uindex"), Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.POST }, true);
    public static final Index EMPLOYEES_SERVICE_NUMBER_UINDEX = Internal.createIndex(DSL.name("Employees_service_number_uindex"), Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.SERVICE_NUMBER }, true);
    public static final Index TESTS_CODE_UINDEX = Internal.createIndex(DSL.name("Tests_code_uindex"), Tests.TESTS, new OrderField[] { Tests.TESTS.CODE }, true);
    public static final Index TESTS_QUESTIONS_UINDEX = Internal.createIndex(DSL.name("Tests_questions_uindex"), Tests.TESTS, new OrderField[] { Tests.TESTS.QUESTIONS }, true);
}
