/*
 * This file is generated by jOOQ.
 */
package domains;


import domains.tables.Answers;
import domains.tables.Branches;
import domains.tables.Employees;
import domains.tables.Organizations;
import domains.tables.Positions;
import domains.tables.Questions;
import domains.tables.Roles;
import domains.tables.Testing;
import domains.tables.Tests;
import domains.tables.records.AnswersRecord;
import domains.tables.records.BranchesRecord;
import domains.tables.records.EmployeesRecord;
import domains.tables.records.OrganizationsRecord;
import domains.tables.records.PositionsRecord;
import domains.tables.records.QuestionsRecord;
import domains.tables.records.RolesRecord;
import domains.tables.records.TestingRecord;
import domains.tables.records.TestsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AnswersRecord> ANSWERS__ANSWERS_PK = Internal.createUniqueKey(Answers.ANSWERS, DSL.name("Answers_pk"), new TableField[] { Answers.ANSWERS.ANSWER_ID, Answers.ANSWERS.QUESTION }, true);
    public static final UniqueKey<BranchesRecord> BRANCHES__ = Internal.createUniqueKey(Branches.BRANCHES, DSL.name(""), new TableField[] { Branches.BRANCHES.BRANCH_ID }, true);
    public static final UniqueKey<EmployeesRecord> EMPLOYEES__ = Internal.createUniqueKey(Employees.EMPLOYEES, DSL.name(""), new TableField[] { Employees.EMPLOYEES.EMPLOYEE_ID }, true);
    public static final UniqueKey<OrganizationsRecord> ORGANIZATIONS__ = Internal.createUniqueKey(Organizations.ORGANIZATIONS, DSL.name(""), new TableField[] { Organizations.ORGANIZATIONS.ORGANIZATION_ID }, true);
    public static final UniqueKey<PositionsRecord> POSITIONS__ = Internal.createUniqueKey(Positions.POSITIONS, DSL.name(""), new TableField[] { Positions.POSITIONS.POSITIONS_ID }, true);
    public static final UniqueKey<QuestionsRecord> QUESTIONS__QUESTIONS_PK = Internal.createUniqueKey(Questions.QUESTIONS, DSL.name("Questions_pk"), new TableField[] { Questions.QUESTIONS.QUESTION_ID, Questions.QUESTIONS.TEST }, true);
    public static final UniqueKey<RolesRecord> ROLES__ = Internal.createUniqueKey(Roles.ROLES, DSL.name(""), new TableField[] { Roles.ROLES.ROLE_ID }, true);
    public static final UniqueKey<TestingRecord> TESTING__ = Internal.createUniqueKey(Testing.TESTING, DSL.name(""), new TableField[] { Testing.TESTING.TESTING_ID }, true);
    public static final UniqueKey<TestsRecord> TESTS__ = Internal.createUniqueKey(Tests.TESTS, DSL.name(""), new TableField[] { Tests.TESTS.TEST_ID }, true);
}
