/*
 * This file is generated by jOOQ.
 */
package domains;


import domains.tables.Answers;
import domains.tables.Branches;
import domains.tables.Employees;
import domains.tables.Organizations;
import domains.tables.Positions;
import domains.tables.Questions;
import domains.tables.Roles;
import domains.tables.SqliteSequence;
import domains.tables.Testing;
import domains.tables.Tests;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Answers</code>.
     */
    public static final Answers ANSWERS = Answers.ANSWERS;

    /**
     * The table <code>Branches</code>.
     */
    public static final Branches BRANCHES = Branches.BRANCHES;

    /**
     * The table <code>Employees</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>Organizations</code>.
     */
    public static final Organizations ORGANIZATIONS = Organizations.ORGANIZATIONS;

    /**
     * The table <code>Positions</code>.
     */
    public static final Positions POSITIONS = Positions.POSITIONS;

    /**
     * The table <code>Questions</code>.
     */
    public static final Questions QUESTIONS = Questions.QUESTIONS;

    /**
     * The table <code>Roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>Testing</code>.
     */
    public static final Testing TESTING = Testing.TESTING;

    /**
     * The table <code>Tests</code>.
     */
    public static final Tests TESTS = Tests.TESTS;
}
