/*
 * This file is generated by jOOQ.
 */
package domains.tables;


import domains.DefaultSchema;
import domains.Indexes;
import domains.Keys;
import domains.tables.records.BranchesRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Branches extends TableImpl<BranchesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Branches</code>
     */
    public static final Branches BRANCHES = new Branches();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BranchesRecord> getRecordType() {
        return BranchesRecord.class;
    }

    /**
     * The column <code>Branches.Branch_id</code>.
     */
    public final TableField<BranchesRecord, Integer> BRANCH_ID = createField(DSL.name("Branch_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Branches.name</code>.
     */
    public final TableField<BranchesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Branches.address</code>.
     */
    public final TableField<BranchesRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>Branches.organization_id</code>.
     */
    public final TableField<BranchesRecord, Integer> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Branches(Name alias, Table<BranchesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Branches(Name alias, Table<BranchesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Branches</code> table reference
     */
    public Branches(String alias) {
        this(DSL.name(alias), BRANCHES);
    }

    /**
     * Create an aliased <code>Branches</code> table reference
     */
    public Branches(Name alias) {
        this(alias, BRANCHES);
    }

    /**
     * Create a <code>Branches</code> table reference
     */
    public Branches() {
        this(DSL.name("Branches"), null);
    }

    public <O extends Record> Branches(Table<O> child, ForeignKey<O, BranchesRecord> key) {
        super(child, key, BRANCHES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.BRANCHES_ORGANIZATION_ID_UINDEX);
    }

    @Override
    public Identity<BranchesRecord, Integer> getIdentity() {
        return (Identity<BranchesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BranchesRecord> getPrimaryKey() {
        return Keys.BRANCHES__;
    }

    @Override
    public Branches as(String alias) {
        return new Branches(DSL.name(alias), this);
    }

    @Override
    public Branches as(Name alias) {
        return new Branches(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Branches rename(String name) {
        return new Branches(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Branches rename(Name name) {
        return new Branches(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
